In [1]:
import json

# Unidad 3: Ejercicios sobre Programación Orientada a Objetos

En estos ejercicos vamos a programar desde cero una aplicación **MUY** básica para gestionar una biblioteca. En ella podremos gestionar los libros, los usuarios, buscar libros, así como permitir prestar libros a los usuarios y que estos lo devuelvan.

### Ejercicio 1: Crear la Clase Libro

**Propósito:** Representar un libro en la biblioteca.

**Atributos:**

- `titulo` (str): Título del libro.

- `autor` (str): Autor del libro.

- `isbn` (str): Identificador único.

- `disponible (bool)`: Si está disponible para préstamo.

**Métodos:**

- `__init__`: Inicializa el libro. Recibe el título, el autor y el isbn.

- `__str__`: Devuelve una representación legible.

    **Ejemplo:** `'El Señor de los Anillos' por J. R. R. Tolkien (ISBN: 9788445003022)`

- `__eq__`: Devuelve `True` si el libro con el que se compara tiene el mismo ISBN.

In [48]:
class Libro:
    def __init__(self, titulo: str, autor: str, isbn: str, disponible=None):
        self.titulo = titulo
        self.autor = autor
        self.isbn = isbn
        self.disponible = disponible

    def __str__(self) -> str:
        return f'{self.titulo} por {self.autor} (ISBN: {self.isbn})'

    def __eq__(self, otro) -> bool:
        return self.isbn == otro.isbn

### Ejercicio 2: Crear la Clase Usuario

**Propósito:** Representar a un usuario que puede pedir libros prestados.

**Atributos:**

- `nombre` (str): Nombre del usuario.

- `id_usuario` (str): ID único.

- `libros_prestados` (list): Lista de libros prestados.

**Métodos:**

- `__init__`: Inicializa el usuario con identificador y nombre de usuario.

- `__str__`: Devuelve el identificador y el nombre del usuario.

    **Ejemplo:** `U001 - Pedro`

- `__eq__`: Devuelve `True` si el usuario con el que se comprar tiene mismo ID.


In [18]:
class Usuario:
    def __init__(self, nombre: str, id_usuario: str, libros_prestados=[]):
        self.nombre = nombre
        self.id_usuario = id_usuario
        self.libros_prestados = libros_prestados

    def __str__(self) -> str:
        return f'{self.id_usuario} - {self.nombre}'

    def __eq__(self, otro) -> bool:
        return self.id_usuario == otro.id_usuario

### Ejercicio 3: Crear la Clase Biblioteca

**Propósito:** Gestionar todos los libros y usuarios.

**Atributos:**

- `libros` (dict): Diccionario de objetos Libro. Clave ISBN, valor objeto Libro

- `usuarios` (dict): Diccionario de objetos Usuario. Calve ID, valor objeto Usuario

**Métodos básicos:**

- `agregar_libro`: Añade un libro a la biblioteca.

- `agregar_usuario`: Registra un nuevo usuario.

- `listar_libros`: Devuelve una lista de libros. Ordendar por ISBN.

- `listar_usuarios`: Devuelve la lista de usuarios dados de alta en el sistema. Ordenar por ID.

In [45]:
class Biblioteca:
    def __init__(self, libros={}, usuarios={}):
        # Key: ISBN, value: object Libro
        self.libros = libros
        # Key: ID, value: object User
        self.usuarios = usuarios

    def agregar_libro(self, libro: Libro):
        if libro.isbn not in self.libros:
            self.libros[libro.isbn] = libro
        else:
            print(f'{libro.titulo} is already in Library')

    def agregar_usuario(self, usuario: Usuario):
        if usuario.id_usuario not in self.usuarios:
            self.usuarios[usuario.id_usuario] = usuario
        else:
            print(f'{usuario.nombre} is already in Library')

    def listar_libros(self):
        for i, isbn_libro in enumerate(sorted(self.libros.items())):
            isbn = isbn_libro[0]
            libro = isbn_libro[1]
            print(f'{i + 1} | {libro.titulo} por {libro.autor} (ISBN: {isbn})')

    def listar_usuarios(self):
        for i, id_usuario_usuario in enumerate(sorted(self.usuarios.items())):
            id_user = id_usuario_usuario[0]
            user = id_usuario_usuario[1]
            print(f'{i + 1} | {id_user} - {user.nombre}')

### Prueba de los ejercicios 1 a 3

Salida esperada:

```
Libros

1 | 'Cien años de soledad' por García Márquez (ISBN: 9788439732471)
2 | 'El Señor de los Anillos' por J. R. R. Tolkien (ISBN: 9788445003022)

Usuarios

1 | U001 - Pedro
```

In [46]:
biblioteca = Biblioteca()

libro1 = Libro("Cien años de soledad", "García Márquez", "9788439732471")
libro2 = Libro("El Señor de los Anillos", "J. R. R. Tolkien", "9788445003022")

usuario = Usuario("Pedro", "U001")

biblioteca.agregar_libro(libro1)
biblioteca.agregar_libro(libro2)

biblioteca.agregar_usuario(usuario)

print("Libros\n")
biblioteca.listar_libros()
print()
print("Usuarios\n")
biblioteca.listar_usuarios()

Libros

1 | Cien años de soledad por García Márquez (ISBN: 9788439732471)
2 | El Señor de los Anillos por J. R. R. Tolkien (ISBN: 9788445003022)

Usuarios

1 | U001 - Pedro


### Ejercicio 4: Implementar Búsqueda

Añade a Biblioteca:

- `buscar_libro`: Busca un libro por ISBN. Si lo encuentra devolverá un objeto de tipo `Libro`; en caso contrario `None`.

- `buscar_usuario`: Busca un usuario por ID. Si lo encuentra devolverá un objeto de tipo `Usuario`; en caso contrario `None`.

**NOTA**: Copia y pega la implementación que tenías hecha de `Biblioteca` en el ejercicio 3 y añade los métodos.

In [47]:
class Biblioteca:
    def __init__(self, libros={}, usuarios={}):
        # Key: ISBN, value: object Libro
        self.libros = libros
        # Key: ID, value: object User
        self.usuarios = usuarios

    def agregar_libro(self, libro: Libro):
        if libro.isbn not in self.libros:
            self.libros[libro.isbn] = libro
        else:
            print(f'{libro.titulo} is already in Library')

    def agregar_usuario(self, usuario: Usuario):
        if usuario.id_usuario not in self.usuarios:
            self.usuarios[usuario.id_usuario] = usuario
        else:
            print(f'{usuario.nombre} is already in Library')

    def listar_libros(self):
        for i, isbn_libro in enumerate(sorted(self.libros.items())):
            isbn = isbn_libro[0]
            libro = isbn_libro[1]
            print(f'{i + 1} | {libro.titulo} por {libro.autor} (ISBN: {isbn})')

    def listar_usuarios(self):
        for i, id_usuario_usuario in enumerate(sorted(self.usuarios.items())):
            id_user = id_usuario_usuario[0]
            user = id_usuario_usuario[1]
            print(f'{i + 1} | {id_user} - {user.nombre}')

    def buscar_libro(self, isbn):
        if isbn in self.libros:
            return self.libros[isbn]
        else:
            return None

    def buscar_usuario(self, user):
        if user in self.usuarios:
            return self.usuarios[user]
        else:
            return None

## Ejercicio 5: Métodos de Préstamo/Devolución en Libro

Añade a Libro:

- `prestar`: Marca el libro como prestado si no está prestado. Devuelve `True` si se ha podido marcar como prestado, en caso contrario, devuelve `False`.

- `devolver`: Lo marca como disponible si está prestado. Devuelve `True` si se ha podido marcar como disponible, en caso contrario, devuelve `False`. 

**NOTA**: Copia y pega la implementación que tenías hecha de `Libro` en el ejercicio 1 y añade los métodos.

In [1]:
class Libro:
    def __init__(self, titulo: str, autor: str, isbn: str, disponible=True):
        self.titulo = titulo
        self.autor = autor
        self.isbn = isbn
        self.disponible = disponible

    def __str__(self) -> str:
        return f'{self.titulo} por {self.autor} (ISBN: {self.isbn})'

    def __eq__(self, otro) -> bool:
        return self.isbn == otro.isbn

    def prestar(self) -> bool:
        if self.disponible:
            self.disponible = False
            return True
        return False
        
    def devolver(self) -> bool:
        if not self.disponible:
            self.disponible = True
            return True
        return False

### Ejercicio 6: Métodos de Préstamo/Devolución en Usuario

Añade a Usuario:

- `prestar_libro:` Añade un libro a libros_prestados si el libro está disponible. Devuelve `True` si se le ha prestado al usuario, en caso contrario `False`

- `devolver_libro:` Elimina un libro de la lista si el libro está prestado al usuario. Devuelve `True` si se ha podido quitar de los libros prestados del usuario, en caso contrario devuelve `False`

- `listar_libros:` Lista los libros que se le han prestado al usuario.

**NOTA**: Copia y pega la implementación que tenías hecha de `Usuario` en el ejercicio 2 y añade los métodos.

In [2]:
class Usuario:
    def __init__(self, nombre: str, id_usuario: str, libros_prestados=[]):
        self.nombre = nombre
        self.id_usuario = id_usuario
        self.libros_prestados = libros_prestados

    def __str__(self) -> str:
        return f'{self.id_usuario} - {self.nombre}'

    def __eq__(self, otro) -> bool:
        return self.id_usuario == otro.id_usuario

    def prestar_libro(self, libro):
        if libro.disponible:
            libro.prestar()
            self.libros_prestados.append(libro)
            return True
        return False

    def devolver_libro(self, libro):
        if libro.devolver():
            self.libros_prestados.remove(libro)
            return True
        return False

### Ejercicio 7: Lógica de Préstamo/Devolución

Añade a Biblioteca:

- `prestar_libro`: Un usuario presta un libro a partir del identicador del usuario y el ISBN del libro. Si encuentra el usuario y el libro, y este no está prestado, se prestará a dicho usuario y delvolverá `True`; en caso contrario devolverá `False`.

- `devolver_libro`: Un usuario devuelve un libro. A partir del identificador del usuario y el ISBN, si el usuario tiene el libro, se devolverá y el método devolverá `True`; en caso contrario devolverá `False`.

Modifica en Biblioteca:

- `listar_libros`: Añadir al lado derecho de cada elemento `- Disponible` o `- Prestado` dependiendo si el libro no está prestado o sí lo está.

**NOTA**: Copia y pega la implementación que tenías hecha de `Biblioteca` en el ejercicio 4 y añade/modifica los métodos.

In [7]:
class Biblioteca:
    def __init__(self, libros={}, usuarios={}):
        # Key: ISBN, value: object Libro
        self.libros = libros
        # Key: ID, value: object User
        self.usuarios = usuarios

    def agregar_libro(self, libro):
        if libro.isbn not in self.libros:
            self.libros[libro.isbn] = libro
        else:
            print(f'{libro.titulo} is already in Library')

    def agregar_usuario(self, usuario):
        if usuario.id_usuario not in self.usuarios:
            self.usuarios[usuario.id_usuario] = usuario
        else:
            print(f'{usuario.nombre} is already in Library')

    def listar_libros(self):
        for i, isbn_libro in enumerate(sorted(self.libros.items())):
            isbn = isbn_libro[0]
            libro = isbn_libro[1]
            if libro.disponible:
                dispo = 'Disponible'
            else:
                dispo = 'Prestado'
            print(f'{i + 1} | {libro.titulo} por {libro.autor} (ISBN: {isbn}) - {dispo}')

    def listar_usuarios(self):
        for i, id_usuario_usuario in enumerate(sorted(self.usuarios.items())):
            id_user = id_usuario_usuario[0]
            user = id_usuario_usuario[1]
            print(f'{i + 1} | {id_user} - {user.nombre}')

    def buscar_libro(self, isbn):
        if isbn in self.libros:
            return self.libros[isbn]
        else:
            return None

    def buscar_usuario(self, user):
        if user in self.usuarios:
            return self.usuarios[user]
        else:
            return None

    def prestar_libro(self, user_id, isbn):
        if isbn in self.libros:
            libro = self.libros[isbn]
            dispo = libro.disponible
            if user_id in self.usuarios and dispo:
                user = self.usuarios[user_id]
                return user.prestar_libro(libro)
        return False

    def devolver_libro(self, user_id, isbn):
        if user_id in self.usuarios:
            user = self.usuarios[user_id]
            libro = self.libros[isbn]
            if libro in user.libros_prestados:
                return user.devolver_libro(libro)
        return False

## Prueba de los ejercicos del 4 al 7

Salida esperada
```
Libros

1 | 'Cien años de soledad' por García Márquez (ISBN: 9788439732471) - Disponible
2 | 'El Señor de los Anillos' por J. R. R. Tolkien (ISBN: 9788445003022) - Disponible

Usuarios

1 | U001 - Pedro
2 | U002 - Ana

--------------------

Prueba búsqueda de usuarios
El libro '9788445003022' está en el sistema.
El libro '9788445003023' NO está en el sistema

Prueba búsqueda de usuarios
El usuario 'U0001' está en el sistema.
El usuario 'U0003' NO está en el sistema

--------------------

Prueba prestamo libros
El libro '9788445003022' se ha prestado al usuario 'U001': Correctamente
El libro '9788445003022' se ha prestado al usuario 'U002': Incorrectamente
El libro '9788439732471' se ha prestado al usuario 'U003': Incorrectamente

Libros
1 | 'Cien años de soledad' por García Márquez (ISBN: 9788439732471) - Disponible
2 | 'El Señor de los Anillos' por J. R. R. Tolkien (ISBN: 9788445003022) - Prestado

--------------------

Prueba devolución libros
El libro '9788445003022' ha sido devuelto por el usuario 'U001': Correctamente
El libro '9788445003022' ha sido devuelto por el usuario 'U001': Incorrectamente
El libro '9788445003022' ha sido devuelto por el usuario 'U001': Incorrectamente

Libros
1 | 'Cien años de soledad' por García Márquez (ISBN: 9788439732471) - Disponible
2 | 'El Señor de los Anillos' por J. R. R. Tolkien (ISBN: 9788445003022) - Disponible

--------------------
```

In [8]:
biblioteca = Biblioteca()

libro1 = Libro("Cien años de soledad", "García Márquez", "9788439732471")
libro2 = Libro("El Señor de los Anillos", "J. R. R. Tolkien", "9788445003022")

usuario1 = Usuario("Pedro", "U001")
usuario2 = Usuario("Ana", "U002")

biblioteca.agregar_libro(libro1)
biblioteca.agregar_libro(libro2)

biblioteca.agregar_usuario(usuario1)
biblioteca.agregar_usuario(usuario2)

print("Libros\n")
biblioteca.listar_libros()
print()
print("Usuarios\n")
biblioteca.listar_usuarios()

print("\n", "-" * 20, sep="")

print("\nPrueba búsqueda de usuarios")
print("El libro '9788445003022'", "está en el sistema." if biblioteca.buscar_libro("9788445003022") is not None else "NO está en el sistema")
print("El libro '9788445003023'", "está en el sistema." if biblioteca.buscar_libro("9788445003023") is not None else "NO está en el sistema")

print("\nPrueba búsqueda de usuarios")
print("El usuario 'U0001'", "está en el sistema." if biblioteca.buscar_usuario("U001") is not None else "NO está en el sistema")
print("El usuario 'U0003'", "está en el sistema." if biblioteca.buscar_usuario("U003") is not None else "NO está en el sistema")

print("\n", "-" * 20, sep="")

print("\nPrueba prestamo libros")

print(
    "El libro '9788445003022' se ha prestado al usuario 'U001':",
    "Correctamente" if biblioteca.prestar_libro("U001", "9788445003022") else "Incorrectamente"
)

print(
    "El libro '9788445003022' se ha prestado al usuario 'U002':",
    "Correctamente" if biblioteca.prestar_libro("U002", "9788445003022") else "Incorrectamente"
)

print(
    "El libro '9788439732471' se ha prestado al usuario 'U003':",
    "Correctamente" if biblioteca.prestar_libro("U003", "9788439732471") else "Incorrectamente"
)

print("\nLibros")
biblioteca.listar_libros()

print("\n", "-" * 20, sep="")

print("\nPrueba devolución libros")

print(
    "El libro '9788445003022' ha sido devuelto por el usuario 'U001':",
    "Correctamente" if biblioteca.devolver_libro("U001", "9788445003022") else "Incorrectamente"
)

print(
    "El libro '9788445003022' ha sido devuelto por el usuario 'U001':",
    "Correctamente" if biblioteca.devolver_libro("U001", "9788445003022") else "Incorrectamente"
)

print(
    "El libro '9788445003022' ha sido devuelto por el usuario 'U001':",
    "Correctamente" if biblioteca.devolver_libro("U002", "9788439732471") else "Incorrectamente"
)

print("\nLibros")
biblioteca.listar_libros()

print("\n", "-" * 20, sep="")


Libros

1 | Cien años de soledad por García Márquez (ISBN: 9788439732471) - Disponible
2 | El Señor de los Anillos por J. R. R. Tolkien (ISBN: 9788445003022) - Disponible

Usuarios

1 | U001 - Pedro
2 | U002 - Ana

--------------------

Prueba búsqueda de usuarios
El libro '9788445003022' está en el sistema.
El libro '9788445003023' NO está en el sistema

Prueba búsqueda de usuarios
El usuario 'U0001' está en el sistema.
El usuario 'U0003' NO está en el sistema

--------------------

Prueba prestamo libros
El libro '9788445003022' se ha prestado al usuario 'U001': Correctamente
El libro '9788445003022' se ha prestado al usuario 'U002': Incorrectamente
El libro '9788439732471' se ha prestado al usuario 'U003': Incorrectamente

Libros
1 | Cien años de soledad por García Márquez (ISBN: 9788439732471) - Disponible
2 | El Señor de los Anillos por J. R. R. Tolkien (ISBN: 9788445003022) - Prestado

--------------------

Prueba devolución libros
El libro '9788445003022' ha sido devuelto por el

### Ejercicio 8: Validar datos en Biblioteca


Modifica los siguientes métodos:

- `agregar_usuario`: Si el usuario ya existe (mismo ID), no se añade a la base de datos y devuelve `False`. En caso de que se pueda añadir el usuario, devuelve `True`.
- `agregar_libro`: Si el libro ya existe (mismo ISBN), no se añade a la base de datos y devuelve `False`. En caso de que se pueda añadir el libro, devuelve `True`.

**NOTA**: Copia y pega la implementación que tenías hecha de `Biblioteca` en el ejercicio 7 y modifica los métodos.

In [9]:
class Biblioteca:
    def __init__(self, libros={}, usuarios={}):
        # Key: ISBN, value: object Libro
        self.libros = libros
        # Key: ID, value: object User
        self.usuarios = usuarios

    def agregar_libro(self, libro):
        if libro.isbn not in self.libros:
            self.libros[libro.isbn] = libro
            return True
        else:
            return False

    def agregar_usuario(self, usuario):
        if usuario.id_usuario not in self.usuarios:
            self.usuarios[usuario.id_usuario] = usuario
            return True
        else:
            return False

    def listar_libros(self):
        for i, isbn_libro in enumerate(sorted(self.libros.items())):
            isbn = isbn_libro[0]
            libro = isbn_libro[1]
            if libro.disponible:
                dispo = 'Disponible'
            else:
                dispo = 'Prestado'
            print(f'{i + 1} | {libro.titulo} por {libro.autor} (ISBN: {isbn}) - {dispo}')

    def listar_usuarios(self):
        for i, id_usuario_usuario in enumerate(sorted(self.usuarios.items())):
            id_user = id_usuario_usuario[0]
            user = id_usuario_usuario[1]
            print(f'{i + 1} | {id_user} - {user.nombre}')

    def buscar_libro(self, isbn):
        if isbn in self.libros:
            return self.libros[isbn]
        else:
            return None

    def buscar_usuario(self, user):
        if user in self.usuarios:
            return self.usuarios[user]
        else:
            return None

    def prestar_libro(self, user_id, isbn):
        if isbn in self.libros:
            libro = self.libros[isbn]
            dispo = libro.disponible
            if user_id in self.usuarios and dispo:
                user = self.usuarios[user_id]
                return user.prestar_libro(libro)
        return False

    def devolver_libro(self, user_id, isbn):
        if user_id in self.usuarios:
            user = self.usuarios[user_id]
            libro = self.libros[isbn]
            if libro in user.libros_prestados:
                return user.devolver_libro(libro)
        return False

### Prueba ejercicio 8

Salida esperada:

```
El usuario 'Ana' con id 'U001' se ha añadido: Correctamente
El usuario 'Ana' con id 'U001' se ha añadido: Incorrectamente
El usuario 'Carlos' con id 'U001' se ha añadido: Incorrectamente

El libro 'Cien años de soledad' con ISBN '9788439732471' se ha añadido: Correctamente
El libro 'Cien años de soledad' con ISBN '9788439732471' se ha añadido: Incorrectamente
El libro 'El Señor de los Anillos' con ISBN '9788439732471' se ha añadido: Incorrectamente

Libros
1 | 'Cien años de soledad' por García Márquez (ISBN: 9788439732471) - Disponible

Usuarios
1 | U001 - Ana
```

In [10]:
biblioteca = Biblioteca()

usuario1 = Usuario("Ana", "U001")
usuario2 = Usuario("Carlos", "U001")

for usu in [usuario1, usuario1, usuario2]:
    print(
        f"El usuario '{usu.nombre}' con id '{usu.id_usuario}' se ha añadido:",
        "Correctamente" if biblioteca.agregar_usuario(usu) else "Incorrectamente"
    )

print()

libro1 = Libro("Cien años de soledad", "García Márquez", "9788439732471")
# Notese el mismo ISBN
libro2 = Libro("El Señor de los Anillos", "J. R. R. Tolkien", "9788439732471")

for lib in [libro1, libro1, libro2]:
    print(
        f"El libro '{lib.titulo}' con ISBN '{lib.isbn}' se ha añadido:",
        "Correctamente" if biblioteca.agregar_libro(lib) else "Incorrectamente"
    )

print()

print("Libros")
biblioteca.listar_libros()
print()
print("Usuarios")
biblioteca.listar_usuarios()


El usuario 'Ana' con id 'U001' se ha añadido: Correctamente
El usuario 'Ana' con id 'U001' se ha añadido: Incorrectamente
El usuario 'Carlos' con id 'U001' se ha añadido: Incorrectamente

El libro 'Cien años de soledad' con ISBN '9788439732471' se ha añadido: Correctamente
El libro 'Cien años de soledad' con ISBN '9788439732471' se ha añadido: Incorrectamente
El libro 'El Señor de los Anillos' con ISBN '9788439732471' se ha añadido: Incorrectamente

Libros
1 | Cien años de soledad por García Márquez (ISBN: 9788439732471) - Disponible

Usuarios
1 | U001 - Ana


### Ejercicio 9: Guardar y cargar datos

Implementar el siguiente método en la clase `Biblioteca`:
- `to_dict`: Devuelve un diccionario con tres claves `usuarios`, `libros`, `prestamos`. Cada entrada será una lista de tuplas:
    - `usuarios`: Lista de tuplas del estilo (`id_usuario`, `nombre`)
    - `libros`: Lista de tuplas del estilo (`isbn`, `titulo`, `autor`)
    - `prestamos`: Lista de tuplas del estilo (`id_usuario`, `isbn`)

- `guardar`: Dada una ruta a un fichero JSON, guarda en ese JSON **único** la lista de usuarios, libros y relación de libros prestados

Implementar el siguiente método **estático** en la clase `Biblioteca`:

- `cargar`: Dado la ruta de un fichero JSON, carga los usuarios y libros, así como la relación de libros prestados. El método devolverá un objeto de tipo `Biblioteca`.


**NOTA**: Copia y pega la implementación que tenías hecha de `Biblioteca` en el ejercicio 8 y modifica los métodos.



In [24]:
class Biblioteca:
    def __init__(self, libros={}, usuarios={}):
        # Key: ISBN, value: object Libro
        self.libros = libros
        # Key: ID, value: object User
        self.usuarios = usuarios

    def agregar_libro(self, libro):
        if libro.isbn not in self.libros:
            self.libros[libro.isbn] = libro
            return True
        else:
            return False

    def agregar_usuario(self, usuario):
        if usuario.id_usuario not in self.usuarios:
            self.usuarios[usuario.id_usuario] = usuario
            return True
        else:
            return False

    def listar_libros(self):
        for i, isbn_libro in enumerate(sorted(self.libros.items())):
            isbn = isbn_libro[0]
            libro = isbn_libro[1]
            if libro.disponible:
                dispo = 'Disponible'
            else:
                dispo = 'Prestado'
            print(f'{i + 1} | {libro.titulo} por {libro.autor} (ISBN: {isbn}) - {dispo}')

    def listar_usuarios(self):
        for i, id_usuario_usuario in enumerate(sorted(self.usuarios.items())):
            id_user = id_usuario_usuario[0]
            user = id_usuario_usuario[1]
            print(f'{i + 1} | {id_user} - {user.nombre}')

    def buscar_libro(self, isbn):
        if isbn in self.libros:
            return self.libros[isbn]
        else:
            return None

    def buscar_usuario(self, user):
        if user in self.usuarios:
            return self.usuarios[user]
        else:
            return None

    def prestar_libro(self, user_id, isbn):
        if isbn in self.libros:
            libro = self.libros[isbn]
            dispo = libro.disponible
            if user_id in self.usuarios and dispo:
                user = self.usuarios[user_id]
                return user.prestar_libro(libro)
        return False

    def devolver_libro(self, user_id, isbn):
        if user_id in self.usuarios:
            user = self.usuarios[user_id]
            libro = self.libros[isbn]
            if libro in user.libros_prestados:
                return user.devolver_libro(libro)
        return False

    def to_dict(self):
        # (id_user, nombre)
        tuplas_user = []
        # Key: ID, value: object User
        for id_user, user in self.usuarios.items():
            tuplas_user.append((id_user, user.nombre))

        # (isbn, titulo, autor)
        tuplas_libros = []
        # Key: ISBN, value: object Libro
        for isbn, libro in self.libros.items():
            tuplas_libros.append((isbn, libro.titulo, libro.autor))

        # (id_user, isbn)
        tuplas_prestamos = []
        for id_user, user in self.usuarios.items():
            for isbn, libro in self.libros.items():
                if libro in user.libros_prestados:
                    tuplas_prestamos.append((id_user, isbn))
        
        return {'usuarios': tuplas_user, 'libros': tuplas_libros, 'prestamos': tuplas_prestamos}

    def guardar(self, path):
        with open(path, 'w', encoding='utf-8') as ofile:
            json.dump(self.to_dict(), ofile)

    @staticmethod
    def cargar(path):
        with open(path, 'r', encoding='utf-8') as ifile:
            attr = json.load(ifile)

        # (id_user, nombre) -> tuplas_user = []
        # (isbn, titulo, autor) -> tuplas_libros
        # (id_user, isbn) -> tuplas_prestamos
        
        # Key: ISBN, value: object Libro
        d_libros = {}
        tuplas_libros = attr['libros']
        for isbn, titulo, autor in tuplas_libros:
            d_libros[isbn] = Libro(titulo, autor, isbn)
            
        # Key: ID, value: object User
        tuplas_user = attr['usuarios']
        d_usuarios = {}
            
        for id_user1, user_name in tuplas_user:
            lista_libros = []
            for id_user2, isbn in attr['prestamos']:
                if id_user1 == id_user2:
                    lista_libros.append(d_libros[isbn])
            d_usuarios[id_user1] = Usuario(user_name, id_user1, lista_libros)
        
        return Biblioteca(d_libros, d_usuarios)

### Prueba Ejercicio 9

Salida esperada:

```
Libros
1 | 'Cien años de soledad' por García Márquez (ISBN: 9788439732471) - Disponible
2 | 'El Señor de los Anillos' por J. R. R. Tolkien (ISBN: 9788445003022) - Prestado

Usuarios
1 | U001 - Pedro
2 | U002 - Ana

Guardamos biblioteca en fichero

--------------------

Cargamos biblioteca de fichero

Libros
1 | 'Cien años de soledad' por García Márquez (ISBN: 9788439732471) - Disponible
2 | 'El Señor de los Anillos' por J. R. R. Tolkien (ISBN: 9788445003022) - Prestado

Usuarios
1 | U001 - Pedro
2 | U002 - Ana
```

In [26]:
biblioteca = Biblioteca()

libro1 = Libro("Cien años de soledad", "García Márquez", "9788439732471")
libro2 = Libro("El Señor de los Anillos", "J. R. R. Tolkien", "9788445003022")

usuario1 = Usuario("Pedro", "U001")
usuario2 = Usuario("Ana", "U002")

biblioteca.agregar_libro(libro1)
biblioteca.agregar_libro(libro2)

biblioteca.agregar_usuario(usuario1)
biblioteca.agregar_usuario(usuario2)

biblioteca.prestar_libro("U001", "9788445003022")

print("Libros")
biblioteca.listar_libros()
print()
print("Usuarios")
biblioteca.listar_usuarios()
print()

print("Guardamos biblioteca en fichero")
biblioteca.guardar("mi_biblioteca.json")
print()
print("-" * 20)
print()

print("Cargamos biblioteca de fichero\n")

biblioteca2 = Biblioteca.cargar("mi_biblioteca.json")

print("Libros")
biblioteca2.listar_libros()
print()
print("Usuarios")
biblioteca2.listar_usuarios()

Libros
1 | Cien años de soledad por García Márquez (ISBN: 9788439732471) - Disponible
2 | El Señor de los Anillos por J. R. R. Tolkien (ISBN: 9788445003022) - Prestado

Usuarios
1 | U001 - Pedro
2 | U002 - Ana

Guardamos biblioteca en fichero

--------------------

Cargamos biblioteca de fichero

Libros
1 | Cien años de soledad por García Márquez (ISBN: 9788439732471) - Disponible
2 | El Señor de los Anillos por J. R. R. Tolkien (ISBN: 9788445003022) - Disponible

Usuarios
1 | U001 - Pedro
2 | U002 - Ana


### Ejercicio 10: Interfaz de usuario interativa 

Completar el código de abajo para crear un menú de usuario interativo

In [27]:
def menu():
    # COMPLETAR
    def show_menu():
        print()
        print("\n--- MENÚ BIBLIOTECA ---")
        print("1. Listar libros")
        print("2. Listar usuarios")
        print("3. Agregar libro")
        print("4. Agregar usuario")
        print("5. Prestar libro")
        print("6. Devolver libro")
        print("7. Guardar datos")
        print("8. Cargar datos")
        print("9. Salir")
        print()

    while True:
        show_menu()
        opcion = int(input("Seleccione una opción: "))

        if opcion == 1:
            # COMPLETAR
            biblioteca.listar_libros()

        elif opcion == 2:
            # COMPLETAR
            biblioteca.listar_usuarios()

        elif opcion == 3: 
            titulo = input("Título: ")
            autor = input("Autor: ")
            isbn = input("ISBN: ")

            # COMPLETAR
            book = Libro(titulo, autor, isbn)
            biblioteca.agregar_libro(book)
            
        elif opcion == 4: 
            id_usuario = input("ID Usuario: ")
            nombre = input("Nombre: ")

            # COMPLETAR
            user = Usuario(nombre, id_usuario)
            biblioteca.agregar_usuario(user)
            
        elif opcion == 5:
            id_usuario = input("ID Usuario: ")
            isbn = input("ISBN del libro: ")

            # COMPLETAR
            biblioteca.prestar_libro(id_usuario, isbn)

        elif opcion == 6:
            id_usuario = input("ID Usuario: ")
            isbn = input("ISBN del libro: ")

            # COMPLETAR
            biblioteca.devolver_libro(id_usuario, isbn)

        elif opcion == 7:
            # COMPLETAR
            path = input('Introduce un path (ej: "menu_bib_final.txt"): ')
            biblioteca.guardar(path)

        elif opcion == 8:
            # COMPLETAR
            path = input('Introduce un path (ej: "menu_bib_final.txt"): ')
            Biblioteca.cargar(path)
        
        elif opcion == 9:
            break

In [28]:
# Ejecuta de forma interactiva el programa

menu()



--- MENÚ BIBLIOTECA ---
1. Listar libros
2. Listar usuarios
3. Agregar libro
4. Agregar usuario
5. Prestar libro
6. Devolver libro
7. Guardar datos
8. Cargar datos
9. Salir



Seleccione una opción:  1


1 | Cien años de soledad por García Márquez (ISBN: 9788439732471) - Disponible
2 | El Señor de los Anillos por J. R. R. Tolkien (ISBN: 9788445003022) - Prestado


--- MENÚ BIBLIOTECA ---
1. Listar libros
2. Listar usuarios
3. Agregar libro
4. Agregar usuario
5. Prestar libro
6. Devolver libro
7. Guardar datos
8. Cargar datos
9. Salir



Seleccione una opción:  2


1 | U001 - Pedro
2 | U002 - Ana


--- MENÚ BIBLIOTECA ---
1. Listar libros
2. Listar usuarios
3. Agregar libro
4. Agregar usuario
5. Prestar libro
6. Devolver libro
7. Guardar datos
8. Cargar datos
9. Salir



Seleccione una opción:  4
ID Usuario:  U005
Nombre:  Jesús




--- MENÚ BIBLIOTECA ---
1. Listar libros
2. Listar usuarios
3. Agregar libro
4. Agregar usuario
5. Prestar libro
6. Devolver libro
7. Guardar datos
8. Cargar datos
9. Salir



Seleccione una opción:  2


1 | U001 - Pedro
2 | U002 - Ana
3 | U005 - Jesús


--- MENÚ BIBLIOTECA ---
1. Listar libros
2. Listar usuarios
3. Agregar libro
4. Agregar usuario
5. Prestar libro
6. Devolver libro
7. Guardar datos
8. Cargar datos
9. Salir



Seleccione una opción:  3
Título:  Viaje al centro de la tierra
Autor:  Julio Verne
ISBN:  9788439999999




--- MENÚ BIBLIOTECA ---
1. Listar libros
2. Listar usuarios
3. Agregar libro
4. Agregar usuario
5. Prestar libro
6. Devolver libro
7. Guardar datos
8. Cargar datos
9. Salir



Seleccione una opción:  1


1 | Cien años de soledad por García Márquez (ISBN: 9788439732471) - Disponible
2 | Viaje al centro de la tierra por Julio Verne (ISBN: 9788439999999) - Disponible
3 | El Señor de los Anillos por J. R. R. Tolkien (ISBN: 9788445003022) - Prestado


--- MENÚ BIBLIOTECA ---
1. Listar libros
2. Listar usuarios
3. Agregar libro
4. Agregar usuario
5. Prestar libro
6. Devolver libro
7. Guardar datos
8. Cargar datos
9. Salir



Seleccione una opción:  5
ID Usuario:  U005
ISBN del libro:  9788439999999




--- MENÚ BIBLIOTECA ---
1. Listar libros
2. Listar usuarios
3. Agregar libro
4. Agregar usuario
5. Prestar libro
6. Devolver libro
7. Guardar datos
8. Cargar datos
9. Salir



Seleccione una opción:  1


1 | Cien años de soledad por García Márquez (ISBN: 9788439732471) - Disponible
2 | Viaje al centro de la tierra por Julio Verne (ISBN: 9788439999999) - Prestado
3 | El Señor de los Anillos por J. R. R. Tolkien (ISBN: 9788445003022) - Prestado


--- MENÚ BIBLIOTECA ---
1. Listar libros
2. Listar usuarios
3. Agregar libro
4. Agregar usuario
5. Prestar libro
6. Devolver libro
7. Guardar datos
8. Cargar datos
9. Salir



Seleccione una opción:  7
Introduce un path (ej: "menu_bib_final.txt"):  menu_bib_final.txt




--- MENÚ BIBLIOTECA ---
1. Listar libros
2. Listar usuarios
3. Agregar libro
4. Agregar usuario
5. Prestar libro
6. Devolver libro
7. Guardar datos
8. Cargar datos
9. Salir



Seleccione una opción:  8
Introduce un path (ej: "menu_bib_final.txt"):  menu_bib_final.txt




--- MENÚ BIBLIOTECA ---
1. Listar libros
2. Listar usuarios
3. Agregar libro
4. Agregar usuario
5. Prestar libro
6. Devolver libro
7. Guardar datos
8. Cargar datos
9. Salir



Seleccione una opción:  1


1 | Cien años de soledad por García Márquez (ISBN: 9788439732471) - Disponible
2 | Viaje al centro de la tierra por Julio Verne (ISBN: 9788439999999) - Prestado
3 | El Señor de los Anillos por J. R. R. Tolkien (ISBN: 9788445003022) - Prestado


--- MENÚ BIBLIOTECA ---
1. Listar libros
2. Listar usuarios
3. Agregar libro
4. Agregar usuario
5. Prestar libro
6. Devolver libro
7. Guardar datos
8. Cargar datos
9. Salir



Seleccione una opción:  2


1 | U001 - Pedro
2 | U002 - Ana
3 | U005 - Jesús


--- MENÚ BIBLIOTECA ---
1. Listar libros
2. Listar usuarios
3. Agregar libro
4. Agregar usuario
5. Prestar libro
6. Devolver libro
7. Guardar datos
8. Cargar datos
9. Salir



Seleccione una opción:  6
ID Usuario:  U005
ISBN del libro:  9788439999999




--- MENÚ BIBLIOTECA ---
1. Listar libros
2. Listar usuarios
3. Agregar libro
4. Agregar usuario
5. Prestar libro
6. Devolver libro
7. Guardar datos
8. Cargar datos
9. Salir



Seleccione una opción:  1


1 | Cien años de soledad por García Márquez (ISBN: 9788439732471) - Disponible
2 | Viaje al centro de la tierra por Julio Verne (ISBN: 9788439999999) - Disponible
3 | El Señor de los Anillos por J. R. R. Tolkien (ISBN: 9788445003022) - Prestado


--- MENÚ BIBLIOTECA ---
1. Listar libros
2. Listar usuarios
3. Agregar libro
4. Agregar usuario
5. Prestar libro
6. Devolver libro
7. Guardar datos
8. Cargar datos
9. Salir



Seleccione una opción:  9
